# Generated by Django 2.0.4 on 2018-08-01 15:24

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtcleCates',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('acateid', models.CharField(max_length=32)),
                ('acatename', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('saytime', models.DateTimeField(auto_now_add=True)),
                ('saycontent', tinymce.models.HTMLField()),
                ('posttittle', models.CharField(max_length=40)),
                ('delflag', models.CharField(max_length=1)),
                ('postcate', models.ForeignKey(on_delete=True, to='aac.ArtcleCates')),
                ('uid', models.ForeignKey(on_delete=True, to='apc.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='OptTarget',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('targetid', models.CharField(max_length=32)),
                ('targetname', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='OptType',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('optid', models.CharField(max_length=32)),
                ('optname', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SaySomethings',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('saytime', models.DateTimeField(auto_now_add=True)),
                ('saycontent', tinymce.models.HTMLField()),
                ('delflag', models.CharField(max_length=1)),
                ('uid', models.ForeignKey(on_delete=True, to='apc.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserOperate',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('opuser', models.CharField(max_length=32)),
                ('optime', models.DateTimeField(auto_now_add=True)),
                ('opcontent', tinymce.models.HTMLField(null=True)),
                ('delflag', models.CharField(max_length=1)),
                ('optarget', models.ForeignKey(on_delete=True, to='aac.OptTarget')),
                ('optypeid', models.ForeignKey(on_delete=True, to='aac.OptType')),
            ],
        ),
    ]
