# Generated by Django 2.0.4 on 2018-08-01 15:24

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusFlag',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('sfid', models.CharField(max_length=32)),
                ('sfname', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserCheck',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=32)),
                ('upwd', models.CharField(max_length=50)),
                ('delflag', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('ufullname', models.CharField(max_length=40)),
                ('uphoto', models.CharField(max_length=200)),
                ('umail', models.CharField(max_length=100)),
                ('uphone', models.CharField(max_length=20, null=True)),
                ('uqq', models.CharField(max_length=20, null=True)),
                ('uregtime', models.DateTimeField(auto_now_add=True)),
                ('usexid', models.CharField(max_length=1, null=True)),
                ('ubrith', models.DateTimeField(auto_now=True, null=True)),
                ('upage', tinymce.models.HTMLField(null=True)),
                ('ujob', models.CharField(max_length=200, null=True)),
                ('utaste', models.CharField(max_length=200, null=True)),
                ('ueducation', models.CharField(max_length=200, null=True)),
                ('ulanguage', models.CharField(max_length=200, null=True)),
                ('uregion', models.CharField(max_length=100, null=True)),
                ('uaddress', models.CharField(max_length=200, null=True)),
                ('ubrief', tinymce.models.HTMLField(null=True)),
                ('ucheckid', models.ForeignKey(on_delete=True, to='apc.UserCheck')),
                ('ustatusid', models.ForeignKey(on_delete=True, to='apc.StatusFlag')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('roleid', models.CharField(max_length=32)),
                ('rolename', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='usercheck',
            name='uroleid',
            field=models.ForeignKey(on_delete=True, to='apc.UserRoles'),
        ),
    ]
